package MeseroVista;

import javax.swing.JOptionPane;
import rapifood.entidades.Mesero;
import rapifood.modelo.Conexion;
import rapifood.modelo.MeseroData;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Nahu
 */
public class MeseroVista extends javax.swing.JInternalFrame {

    private MeseroData meseroData;
    private Conexion conexion;

    public MeseroVista() {
        initComponents();
        this.setLocation(310, 50);
        conexion = new Conexion();
        meseroData = new MeseroData(conexion);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlDni = new javax.swing.JLabel();
        jlCuit = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlEstado = new javax.swing.JLabel();
        jtfDni = new javax.swing.JTextField();
        jtfCuit = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfApellido = new javax.swing.JTextField();
        jcbEstado = new javax.swing.JCheckBox();
        jbGuardar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jtfId = new javax.swing.JTextField();
        jlId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbBaja = new javax.swing.JCheckBox();
        jcbAlta = new javax.swing.JCheckBox();
        jbLimpiar = new javax.swing.JButton();
        jbConfirmar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("~Mesero~");
        setRequestFocusEnabled(false);
        setVisible(true);

        jlTitulo.setFont(new java.awt.Font("SF Movie Poster", 0, 48)); // NOI18N
        jlTitulo.setText("~Mesero~");

        jlNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlNombre.setText("Nombre:");

        jlDni.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlDni.setText("DNI:");

        jlCuit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlCuit.setText("CUIT:");

        jlApellido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlApellido.setText("Apellido:");

        jlEstado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlEstado.setText("Estado:");

        jtfDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDniActionPerformed(evt);
            }
        });

        jtfCuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCuitActionPerformed(evt);
            }
        });

        jtfApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfApellidoActionPerformed(evt);
            }
        });

        jcbEstado.setText("Activo");

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbBorrar.setText("Borrar");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jlId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlId.setText("Id:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Dar Alta o Baja:");

        jcbBaja.setText("Baja");
        jcbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBajaActionPerformed(evt);
            }
        });

        jcbAlta.setText("Alta");

        jbLimpiar.setForeground(new java.awt.Color(255, 0, 0));
        jbLimpiar.setText("Limpiar Campos");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jbConfirmar.setText("Confirmar");
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlEstado)
                            .addComponent(jlApellido)
                            .addComponent(jlNombre)
                            .addComponent(jlCuit)
                            .addComponent(jlDni)
                            .addComponent(jlId))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jcbEstado)
                                    .addGap(247, 247, 247)
                                    .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jcbAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtfId)
                                            .addComponent(jtfApellido)
                                            .addComponent(jtfNombre)
                                            .addComponent(jtfCuit)
                                            .addComponent(jtfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jbBuscar))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(184, 184, 184)
                                                .addComponent(jcbBaja))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(66, 66, 66)
                                .addComponent(jbConfirmar))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbGuardar)
                        .addGap(58, 58, 58)
                        .addComponent(jbBorrar)
                        .addGap(59, 59, 59)
                        .addComponent(jbActualizar)))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlTitulo)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlId)
                    .addComponent(jbBuscar))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDni)
                    .addComponent(jtfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbAlta))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jbConfirmar))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCuit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbBaja)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNombre))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlApellido))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbEstado)
                            .addComponent(jlEstado)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar)
                    .addComponent(jbBorrar)
                    .addComponent(jbActualizar))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDniActionPerformed

    private void jtfApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfApellidoActionPerformed

    private void jtfCuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCuitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCuitActionPerformed

    private void jcbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbBajaActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        int x = JOptionPane.showConfirmDialog(this, "Esta seguro que desea GUARDAR el mesero?", "ATENCION!!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (x == JOptionPane.YES_OPTION) {
            int dni = Integer.parseInt(jtfDni.getText());
            int cuit = Integer.parseInt(jtfCuit.getText());
            String nombre = jtfNombre.getText();
            String apellido = jtfApellido.getText();
            boolean estado = jcbEstado.isSelected();
            Mesero mesero = new Mesero(dni, cuit, nombre, apellido, estado);
            meseroData.guardarMesero(mesero);
            jtfId.setText(mesero.getIdMesero() + " ");
            if (jtfNombre.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No puede dejar el campo nombre vacio");
            }
            limpiar();
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        limpiar();

    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        int x = JOptionPane.showConfirmDialog(this, "Esta seguro que desea BORRAR el mesero?", "ATENCION!!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (x == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(jtfId.getText());
            meseroData.borrarMesero(id);
            limpiar();
        }
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        boolean cargado = true;
        if (jtfId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo id esta vacio: " + jtfId.getText(), "ERROR!", JOptionPane.WARNING_MESSAGE);
        }
        if (cargado) {
            int id = Integer.parseInt(jtfId.getText());
            Mesero mesero = meseroData.buscarMesero(id);
            if (mesero != null) {
                jtfId.setText(mesero.getIdMesero() + "");
                jtfDni.setText(mesero.getDni() + "");
                jtfCuit.setText(mesero.getCuit() + "");
                jtfNombre.setText(mesero.getNombre());
                jtfApellido.setText(mesero.getApellido());
                jcbEstado.setSelected(mesero.isEstado());

            }
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        int x = JOptionPane.showConfirmDialog(this, "Esta seguro que modificar el ALTA o BAJA del mesero?", "ATENCION!!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        boolean estado = jcbAlta.isSelected();
        boolean estado2 = jcbBaja.isSelected();
        String id = jtfId.getText();
        if (x == JOptionPane.YES_OPTION) {
            if (estado == true && estado2 == false) {
                meseroData.DarDeAltaMesero(Integer.parseInt(id));
            } else if (estado2 == true && estado == false) {
                meseroData.DarDeBajaMesero(Integer.parseInt(id));
            } else {
                JOptionPane.showMessageDialog(null, "Error debe elegir una sola opcion");
            }

        }
        limpiar();
    }//GEN-LAST:event_jbConfirmarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        int x = JOptionPane.showConfirmDialog(this, "Esta seguro que desea ACTUALIZAR el mesero?", "ATENCION!!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (x == JOptionPane.YES_OPTION) {
            if (jtfId.getText()!= null) {
                String dni = jtfDni.getText();
                String cuit = jtfCuit.getText();
                String nombre = jtfNombre.getText();
                String apellido = jtfApellido.getText();
                boolean estado = jcbEstado.isSelected();
                Mesero mesero = new Mesero(Integer.parseInt(jtfId.getText()),Integer.parseInt(dni),Integer.parseInt(cuit),nombre,apellido,estado);
                meseroData.actualizarMesero(mesero);
                jtfId.setText(mesero.getIdMesero()+"");
                limpiar();
            }
        }
    }//GEN-LAST:event_jbActualizarActionPerformed
    public void limpiar() {
        jtfId.setText("");
        jtfDni.setText("");
        jtfCuit.setText("");
        jtfNombre.setText("");
        jtfApellido.setText("");
        jcbEstado.setSelected(false);
        jcbAlta.setSelected(false);
        jcbBaja.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JCheckBox jcbAlta;
    private javax.swing.JCheckBox jcbBaja;
    private javax.swing.JCheckBox jcbEstado;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlCuit;
    private javax.swing.JLabel jlDni;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfCuit;
    private javax.swing.JTextField jtfDni;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
