/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapifood.vistas.menu.pedido;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rapifood.entidades.DetallePedido;
import rapifood.entidades.Mesa;
import rapifood.entidades.Mesero;
import rapifood.entidades.Pedido;
import rapifood.modelo.Conexion;
import rapifood.modelo.MesaData;
import rapifood.modelo.MeseroData;
import rapifood.modelo.PedidoData;

/**
 *
 * @author Hyouka
 */
public class GuardarPedido extends javax.swing.JInternalFrame {
private DefaultTableModel modelo=new DefaultTableModel();
   PedidoData pd;
   MesaData md;
   MeseroData meseroD;
    public GuardarPedido() {
        initComponents();
        this.setLocation(175, 50);
    Conexion c=new Conexion();
    pd=new PedidoData(c);
    md=new MesaData(c);
    meseroD=new MeseroData(c);
     this.cargarMesas();
        this.cargarMeseros();
        armaCabeceraTabla();
        cargaPedido();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbMesero = new javax.swing.JComboBox<>();
        jcbMesa = new javax.swing.JComboBox<>();
        jcheakEstado = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jbGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbGuardarCambios = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbBuscar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jbAct = new javax.swing.JButton();

        jcheakEstado.setText("Activo");

        jTabla = new javax.swing.JTable(){
            @Override
            public Class<?> getColumnClass(int columna) {

                if(columna==4){
                    return Boolean.class;
                }
                return String.class;
            }
            @Override
            public boolean isCellEditable(int row, int column) {
                if(column==4){
                    return true;}
                return false;
            }
        };
        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabla);

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Guardar Pedido");

        jLabel2.setText("Pedidos");

        jbGuardarCambios.setText("Guardar Cambios");
        jbGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarCambiosActionPerformed(evt);
            }
        });

        jLabel3.setText("Mesas:");

        jLabel4.setText("Meseros:");

        jLabel5.setText("Buscar Pedido");

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbAct.setText("Ver todos los pedidos");
        jbAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbGuardar)
                            .addComponent(jcheakEstado)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(152, 152, 152)
                        .addComponent(jbAct))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbGuardarCambios)
                .addGap(162, 162, 162))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(23, 23, 23)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBuscar)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(jbAct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jbBuscar))
                        .addGap(6, 6, 6))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jbGuardarCambios)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbMesero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(59, 59, 59)
                        .addComponent(jcheakEstado)
                        .addGap(61, 61, 61)
                        .addComponent(jbGuardar)
                        .addGap(73, 73, 73))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
           int x =JOptionPane.showConfirmDialog(this, "Desea Guardar el pedido?","ATENCION!!",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
            if(x== JOptionPane.YES_OPTION){
        Mesa m=(Mesa)this.jcbMesa.getSelectedItem();
        Mesero mes=(Mesero)this.jcbMesero.getSelectedItem();
        boolean act= this.jcheakEstado.isEnabled();
        Pedido p=new Pedido(m,mes,act);
        pd.guardarPedido(p);
        cargaPedido();
            }      
        
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
         cargaPedidoXFecha();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActActionPerformed
        // TODO add your handling code here:
        cargaPedido();
    }//GEN-LAST:event_jbActActionPerformed

    private void jbGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarCambiosActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this, "Esta seguro ?", "ATENCION!!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (x == JOptionPane.YES_OPTION) {
        int filaSeleccionada=jTabla.getSelectedRow();
        if(filaSeleccionada!=-1){
            int id=(Integer)modelo.getValueAt(filaSeleccionada, 0);
            Pedido p=pd.buscarPedido(id);
            boolean est=(boolean)modelo.getValueAt(filaSeleccionada, 4);
            p.setEstadoPedido(est);
            pd.actualizarPedido(p);
            cargaPedido();
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione un pedido a modificar");
        }
        }
    }//GEN-LAST:event_jbGuardarCambiosActionPerformed
 public void cargarMesas(){
     List<Mesa> mesas=new ArrayList<>();
     mesas.addAll(md.obtenerMesasDisponibles());
      for(Mesa item:mesas){
            jcbMesa.addItem(item);
      }
 }
 public void cargarMeseros(){
          List<Mesero> meseros=meseroD.obtenerMeserosActivos();
      for(Mesero item:meseros){
            jcbMesero.addItem(item);
      }
 }
 public void armaCabeceraTabla(){
           //Titulos de Columnas
        ArrayList<Object> columnas=new ArrayList<Object>();
        columnas.add("Id");
        columnas.add("Mesa");
        columnas.add("Mesero");
        columnas.add("Fecha");
        columnas.add("Estado");
        for(Object it:columnas){
        
            modelo.addColumn(it);
        }
        jTabla.setModel(modelo);
  }

public void borraFilasTabla(){

        int a =modelo.getRowCount()-1;

           for(int i=a;i>=0;i--){
   
                modelo.removeRow(i);
           }
}
public void cargaPedido(){
    
        borraFilasTabla();
           //Llenar filas
        List<Pedido> lista = pd.obtenerPedidos();
        
        for(Pedido p:lista){
        
            modelo.addRow(new Object[]{p.getIdPedido(),p.getMesa(),p.getMesero(),p.getFechaPedido(),p.isEstadoPedido()});
        }
}
public void cargaPedidoXFecha(){
    if(jDateChooser1.getDate()==null){
    JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha valida");
    }else{
        LocalDate fecha = LocalDateTime.ofInstant(jDateChooser1.getDate().toInstant(), ZoneId.systemDefault()).toLocalDate();

        borraFilasTabla();
           //Llenar filas
        List<Pedido> lista = pd.buscarPedidoXFecha(fecha);

        for(Pedido p:lista){
        
            modelo.addRow(new Object[]{p.getIdPedido(),p.getMesa(),p.getMesero(),p.getFechaPedido(),p.isEstadoPedido()});
        }}
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    private javax.swing.JButton jbAct;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbGuardarCambios;
    private javax.swing.JComboBox<Mesa> jcbMesa;
    private javax.swing.JComboBox<Mesero> jcbMesero;
    private javax.swing.JCheckBox jcheakEstado;
    // End of variables declaration//GEN-END:variables
}
