/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapifood.vistas.menu.pedido;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rapifood.entidades.DetallePedido;
import rapifood.entidades.Mesero;
import rapifood.entidades.Pedido;
import rapifood.modelo.Conexion;
import rapifood.modelo.MesaData;
import rapifood.modelo.MeseroData;
import rapifood.modelo.PedidoData;

/**
 *
 * @author Hyouka
 */
public class PedidosXFecha extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo=new DefaultTableModel();
            PedidoData pd;
   MesaData md;
   MeseroData meseroD;
   
    public PedidosXFecha() {
        initComponents();
  
        initComponents();
        this.setLocation(175, 50);
    Conexion c=new Conexion();
    pd=new PedidoData(c);
    md=new MesaData(c);
    meseroD=new MeseroData(c);
    armaCabeceraTabla();
    cargarMeseros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jbBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jcbMesero = new javax.swing.JComboBox<>();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jbBuscar.setText("Buscar por fecha");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabla);

        jButton1.setText("Buscar por mesero");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Mesero:");

        jLabel2.setText("Cierre de Pedidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbMesero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbMesero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscar)
                    .addComponent(jButton1))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        cargaDatosXPedido();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cargaDatosXMesero();
    }//GEN-LAST:event_jButton1ActionPerformed
public void armaCabeceraTabla(){
           //Titulos de Columnas
        ArrayList<Object> columnas=new ArrayList<Object>();
        columnas.add("ID");
        columnas.add("Mesa");
        columnas.add("Mesero");
        columnas.add("Estado");
        columnas.add("Total");
        for(Object it:columnas){
        
            modelo.addColumn(it);
        }
        jTabla.setModel(modelo);
  }

public void borraFilasTabla(){

        int a =modelo.getRowCount()-1;

           for(int i=a;i>=0;i--){
   
                modelo.removeRow(i);
           }
}
public void cargaDatosXPedido(){
     if(jDateChooser1.getDate()==null){
    JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha valida");
    }else{
    int año= jDateChooser1.getCalendar().get(Calendar.YEAR);
    int mes = jDateChooser1.getCalendar().get(Calendar.MONTH);
    int day = jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH);
    
    LocalDate fecha =LocalDate.of(año, ++mes, day);
        borraFilasTabla();
           //Llenar filas
        
        List<Pedido> lista = pd.buscarPedidoXFecha(fecha);
        for(Pedido dp:lista){
        
            modelo.addRow(new Object[]{dp.getIdPedido(),dp.getMesa(),dp.getMesero(),dp.isEstadoPedido(),pd.obtenerTotal(dp.getIdPedido())});
            
        }
    }
}
 public void cargarMeseros(){
          List<Mesero> meseros=meseroD.obtenerMeseros();
      for(Mesero item:meseros){
            jcbMesero.addItem(item);
      }
 }
 public void cargaDatosXMesero(){
     if(jDateChooser2.getDate()==null){
    JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha valida");
    }else{
    int año= jDateChooser2.getCalendar().get(Calendar.YEAR);
    int mes = jDateChooser2.getCalendar().get(Calendar.MONTH);
    int day = jDateChooser2.getCalendar().get(Calendar.DAY_OF_MONTH);
    
    LocalDate fecha =LocalDate.of(año, ++mes, day);
        borraFilasTabla();
           //Llenar filas
        Mesero m=(Mesero)jcbMesero.getSelectedItem();
        List<Pedido> lista = pd.buscarPedidoDeMesero(fecha,m.getIdMesero());
        if(lista.size()==0){
            
        }else{
        for(Pedido dp:lista){
        
            modelo.addRow(new Object[]{dp.getIdPedido(),dp.getMesa(),dp.getMesero(),dp.isEstadoPedido(),pd.obtenerTotal(dp.getIdPedido())});
            
        }
        }
}
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JComboBox<Mesero> jcbMesero;
    // End of variables declaration//GEN-END:variables
}
